name: desktop_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.0
  shared_preferences: ^2.5.3
  internet_connection_checker_plus: ^2.3.0
  uuid: ^4.1.0
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.6
  syncfusion_flutter_pdfviewer: ^24.2.8
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  webview_windows: ^0.4.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/_data/
    - assets/_data/steps/
    - assets/_data/videos/_demo.mp4
    - assets/_data/notes/_demo.pdf
